x

diff --git a/bin/fake_edit b/bin/fake_edit
--- a/bin/fake_edit
+++ b/bin/fake_edit
@@ -3,4 +3,6 @@
 if ! tty -s <&1; then
   exec >/dev/null
 fi
+test -z "$1" && echo>&2 "cannot open '$1'" && exit 1;
 echo "No log message" | tee "$1" 
+
